layout_spectrum: 0.8563763207313374
typography_spectrum: 0.5048914886296423
color:
  brandStrength: 0.5525567115044756
  lightness: 0.9483683681821837
  saturation: 0.19188016480913772
  rhythmicContrast: 0.8610490021045956
  brandColors:
    - '#22B14C'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
