layout_spectrum: 0.34890324022943653
typography_spectrum: 0.9895342864803417
color:
  brandStrength: 0.35641179140103924
  lightness: 1
  saturation: 0.6697496958016096
  rhythmicContrast: 0.6367995208509193
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
