layout_spectrum: 0.46247199927677984
typography_spectrum: 0.5338497252966102
color:
  brandStrength: 0.42029050906668275
  lightness: 0.865554568617245
  saturation: 0.16381309138196012
  rhythmicContrast: 0.7720802437908726
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
