layout_spectrum: 0.5895117260784943
typography_spectrum: 0.8259282105637363
color:
  brandStrength: 0.3145484976432664
  lightness: 1
  saturation: 0.777576968278828
  rhythmicContrast: 0.8111152121270685
  brandColors:
    - '#22B14C'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
