layout_spectrum: 0.5981271424861901
typography_spectrum: 0.7395579465666767
color:
  brandStrength: 0.40389715167693796
  lightness: 0.7300998285520675
  saturation: 0.7753154611245425
  rhythmicContrast: 0.6094234617588359
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
