layout_spectrum: 0.857067461673281
typography_spectrum: 1
color:
  brandStrength: 0.1792858250511091
  lightness: 0.8147827183619364
  saturation: 0.4638121613595487
  rhythmicContrast: 0.13394586191079258
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie
title: ''
content: []
description: ''
