layout_spectrum: 0.4841099701878974
typography_spectrum: 0.4756711739888138
color:
  brandStrength: 0.39544416275806726
  lightness: 0.9131937408828094
  saturation: 0.9260946477881384
  rhythmicContrast: 0.700780293932369
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie
title: ''
content: []
description: ''
