layout_spectrum: 0.8775207255656213
typography_spectrum: 0.5173032403586082
color:
  brandStrength: 0.5106020579159739
  lightness: 0.48989778677813045
  saturation: 0.06947418612298915
  rhythmicContrast: 0.5381627730506076
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
