layout_spectrum: 0.48844956628083813
typography_spectrum: 0.8086697401723244
color:
  brandStrength: 0.0214833603907229
  lightness: 0.11498674492038197
  saturation: 0.7477923256696414
  rhythmicContrast: 0.1412301191996488
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
