layout_spectrum: 0.8449458693408656
typography_spectrum: 0.8274726035426564
color:
  brandStrength: 0.9719174348194115
  lightness: 0.7649428138928027
  saturation: 0.16820581944622467
  rhythmicContrast: 0.9784084808171755
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
