layout_spectrum: 0.9094747402161213
typography_spectrum: 0.8602307602398024
color:
  brandStrength: 0.3313135329746448
  lightness: 0.9539560696649558
  saturation: 0.16103251614589428
  rhythmicContrast: 0.17717630540942866
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
