layout_spectrum: 0.28299181550104946
typography_spectrum: 0.07924715898829596
color:
  brandStrength: 0.35674825936952365
  lightness: 0.7014648999543952
  saturation: 0.7186733041363446
  rhythmicContrast: 0.3247069893859438
  brandColors:
    - '#FF7F27'
    - '#B5E61D'
    - '#FA8526'
    - '#E3A523'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
