layout_spectrum: 0.08921069564629752
typography_spectrum: 0.7363671121963917
color:
  brandStrength: 0.6240223306565924
  lightness: 0.9505672107459885
  saturation: 0.023906179576798685
  rhythmicContrast: 0.14472077630266622
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
