layout_spectrum: 0.61026935248147
typography_spectrum: 0.418825070485196
color:
  brandStrength: 0.7489390522334725
  lightness: 0.26609424165311724
  saturation: 0.6907032925392141
  rhythmicContrast: 0.8445810078044819
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
