layout_spectrum: 0.0470855607541444
typography_spectrum: 0.013495882956845926
color:
  brandStrength: 0.8927954197571715
  lightness: 0.9411891096065024
  saturation: 0.1552503973665177
  rhythmicContrast: 0.26718933158775443
  brandColors:
    - '#FF7F27'
    - '#B5E61D'
    - '#FA8526'
    - '#E3A523'
coverPrefs:
  filter: false
github: true
author:
  name: Krzystos
name: >-
  Nieoficjalny spis tematów  w Q&A na kanale Langusta Na Palmie (przewiń na sam
  dół by wczytać całość)
title: ''
content: []
description: ''
analytics:
  google: UA-103033253-1
